---

  - name: get azure secret  ==>>  {{ _iter_az_secrets.value.config.name | default('<ALL>', True) }}
    azure.azcollection.azure_rm_keyvaultsecret_info: "{{ _iter_az_secrets.value.config }}"
    register: _tmp_get_cur_secrets
    changed_when: false
    no_log: true


  - set_fact:
      get_az_secrets_result: >-
         {{ get_az_secrets_result
          | append_az_secrets(
              new_secrets=_tmp_get_cur_secrets.secrets,
              secrets_cfg=_iter_az_secrets.value
          ) }}
    no_log: true

