---

  - name: get azure secret  ==>>  {{ _cur_getsec_cfg.value.config.name | default('<ALL>', True) }}
    azure.azcollection.azure_rm_keyvaultsecret_info: "{{ _cur_getsec_cfg.value.config }}"
    register: _tmp_get_cur_secrets
    changed_when: false
    no_log: "{{ smabot_az_secrets_args_normed.hide_secrets }}"


  - set_fact:
      smabot_azure_read_secrets: >-
         {{ smabot_azure_read_secrets
          | smabot.azure.append_az_secrets(
              new_secrets=_tmp_get_cur_secrets.secrets,
              secrets_cfg=_cur_getsec_cfg.value,
              base_cfg=smabot_az_secrets_args_normed.get_secrets,
          ) }}
    no_log: "{{ smabot_az_secrets_args_normed.hide_secrets }}"

