---

################### <assure py env is prepared> ######################

  - ansible.builtin.include_role:
      name: smabot.azure.prepare_azure_pip
    vars:
      smabot_azure_prepare_azure_pip_args:
        requirements_srcpath: >-
          {{ smabot_az_secrets_args_normed.requirements_srcpath }}


################### <actually reading secrets> ######################

  - set_fact:
      smabot_azure_read_secrets: {}

  - ansible.builtin.include_tasks: read_secrets.yml
    loop: >-
      {{ smabot_az_secrets_args_normed.get_secrets.secrets | dict2items }}
    loop_control:
      loop_var: _iter_az_secrets
      label: "{{ _iter_az_secrets.key }}"


  - name: return read secrets as flat value list as requested
    set_fact:
      smabot_azure_read_secrets: >-
        {{ smabot_azure_read_secrets | combine({'secrets': (
             smabot_azure_read_secrets.secrets | default({}) | dict2items
             | map(attribute='value') | list), })
        }}
    when: smabot_az_secrets_args_normed.get_secrets.return_list
    no_log: "{{ smabot_az_secrets_args_normed.hide_secrets }}"


################### <writing secrets> #######################

  - ansible.builtin.include_tasks: write_secret.yml
    loop: >-
      {{ smabot_az_secrets_args_normed.set_secrets.secrets | dict2items }}
    loop_control:
      loop_var: _iter_az_secrets
      label: "{{ _iter_az_secrets.key }}"

