---

  - name: set azure secret  ==>>  {{ _iter_az_secrets.value.config.secret_name }}
    azure.azcollection.azure_rm_keyvaultsecret: "{{ _iter_az_secrets.value.config }}"
    changed_when: false
    no_log: "{{ smabot_az_secrets_args_normed.hide_secrets }}"

